### PR TITLE
Fix zombies getting bored and dying

### PR DESCRIPTION
**Pull request by mjkzy**

### CODE REVIEW

**Comment by mjkzy** [comment]
idk bout this

**Comment by JezuzLizard** [comment]
Yeah I kind of modified how the round spawning works, but more investigation should be done into how it should work. It should be possible to do it more similarly to MP with a timelimit, and round limit. Maybe there are only like 10 zombies each round and and killing them all ends the round playing a round ending killcam, and then does a round restart like Grief but then the round increments. Then after like 5 rounds or so the game ends with a final killcam. I guess it depends on whether doing solo trickshotting or coop trickshotting is what the mod wants to do. Maybe for coop it plays a killcam montage of each trickshot done by each player at the end of the game?

The solutions to the zombies dying should work too but I didn't test the distance tracking solution.

**Review by chsedotsh — APPROVED** [review]
Vouch.

**Comment by mjkzy** [comment]
closing as this is just kinda a odd issue and i dont care anymore

**Pull request closed without merging**
